title: Blog
tagline: A Jekyll template
url: https://aflim.github.io
baseurl: /blog
permalink: pretty
paginate: 10

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  
sass:
  sass_dir: _sass
  style: :compressed
  
author:
  name: aflim
  email: aflim@outlook.co.id

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

